- hosts: all
  become: true
  roles:
    - role: docker_deploy
  tags: docker_deploy

- hosts: all
  become: true
  roles:
    - role: get_nginx_data
  tags: get_nginx_data

- hosts: all
  become: true
  roles:
    - role: dockerhost_setup
  tags: dockerhost_setup
