- hosts: base
  become: true
  roles:
    - role: base
  tags: base

- hosts: all
  become: true
  roles:
    - role: mount_setup
  tags: mount_setup

- hosts: all
  become: true
  roles:
    - role: setup_nginx
  tags: setup_nginx

- hosts: all
  become: true
  roles:
    - role: docker_deploy
  tags: docker_deploy

- hosts: localhost
  connection: local
  become: true
  roles:
    - role: kuma_setup
  tags: kuma_setup

- hosts: all
  become: true
  roles:
    - role: prometheus_setup
  tags: prometheus_setup

- hosts: gitea
  become: true
  roles:
    - role: gitea_setup
  tags: gitea_setup

- hosts: all
  become: true
  roles:
    - role: update
  tags: update
