- name: Add Docker APT repository on (Ubuntu, Debian)
  deb822_repository:
    name: docker
    state: present
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution|lower }}"
    suites: ["{{ ansible_distribution_release|lower }}"]
    components: [stable]
    signed_by: "https://download.docker.com/linux/debian/gpg"
    enabled: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]
  notify: Update cache on (Ubuntu, Debian) for Docker repo

- meta: flush_handlers

- name: Install Docker on (Ubuntu, Debian)
  package:
    state: latest
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  when: ansible_distribution in ["Debian", "Ubuntu"]
  
- name: Install Docker on (Alpine)
  apk:
    name:
      - docker
      - docker-cli-compose
  notify: Docker on Alpine
  when: ansible_distribution in ["Alpine"]
