- name: Upgrade apt packages on (Ubuntu, Debian)
  become: true
  apt:
    update_cache: yes
    upgrade: yes
    autoclean: yes
    autoremove: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Upgrade apk packages on (Alpine)
  apk:
    update_cache: true
    upgrade: true
  when: ansible_distribution in ["Alpine"]

- name: Check that the reboot-requied exists
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Automated reboot
  reboot:
  when:
    - reboot_required_file.stat.exists == true
    