- name: Ensure parent directory exists
  ansible.builtin.file:
    path: "{{ loop_var.env_dst | dirname }}"
    state: directory
    mode: '0755'

- name: Fetch template from remote host
  fetch:
    src: "{{ env_template.env_src }}"
    dest: "{{ playbook_dir }}/{{ env_template.env_src | basename }}"
    flat: yes
  loop: "{{ item.value.env_templates }}"
  loop_control:
    loop_var: env_template
    label: "{{ env_template }}"

- name: Apply template
  template:
    src: "{{ playbook_dir }}/{{ env_template.env_src | basename }}"
    dest: "{{ env_template.env_dst }}"
  loop: "{{ item.value.env_templates }}"
  loop_control:
    loop_var: env_template
    label: "{{ env_template }}"
