#- set_fact:
#    service_ip: "{{ ansible_default_ipv4.address }}"
#  when:
#    - loop_var_nginx_data.service_ip is not defined
#
#- set_fact:
#    service_ip: "{{ loop_var_nginx_data.service_ip }}"
#  when:
#    - loop_var_nginx_data.service_ip is defined

- set_fact:
    service_ip: "{{ loop_var_nginx_data.service_ip | default(ansible_default_ipv4.address) }}"
    service_name: "{{ loop_var_nginx_data.service_name | default(item.key) }}"

- blockinfile:
    path: "{{ nginx_conf_dst }}"
    block: |2
        
        - service_name: "{{ service_name }}"
          service_ip:  "{{ service_ip }}"
          service_port: "{{ loop_var_nginx_data.service_port }}"
          service_url: "{{ loop_var_nginx_data.service_url }}"

    marker: ""
    create: true
  when:
    - loop_var_nginx_data.service_name is defined
    - loop_var_nginx_data.service_port is defined
    - loop_var_nginx_data.service_url is defined
