- name: Ensure parent directory exists
  ansible.builtin.file:
    path: "{{ loop_var.env_dst | dirname }}"
    state: directory
    mode: '0755'

- include_tasks: create_envs_template.yml
  loop: "{{ item.value.env_templates }}"
  loop_control:
    loop_var: env_template
    label: "{{ env_template }}"