- name: Check for config dir
  stat:
    path: "{{ item.value.config_repo_dir }}"
  register: config_dir_status
  when:
    - item.value.config_repo_url is defined
    - item.value.config_repo_dir is defined

- name: Restore config
  git:
    repo: "{{ item.value.config_repo_url }}"
    dest: "{{ item.value.config_repo_dir }}"
  when:
    - item.value.config_repo_url is defined
    - item.value.config_repo_dir is defined
    - not config_dir_status.stat.exists
    