- name: test
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - test"
    insertafter: BOF
    block: |
      global:
        scrape_interval: 10s

    

