- name: test
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: "# {mark}"
    insertafter: BOF
    block: |
      global:
        scrape_interval: 10s
        scrape_configs:

- name: test
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: ""
    insertafter: "scrape_configs:"
    block: |2
      - job_name: {{ job_name }}
        static_configs:
          - targets:


- name: Insert line after targets
  lineinfile:
    path: /path/to/your/file
    insertafter: '^.*- targets:.*'
    line: "  - {{ item }}"
    state: present
  loop: "{{ conf_ip_list_name }}"