- name: Create Prometheus file
  file:
    path: "{{ prometheus_config }}"
    state: touch

- name: Create glboal
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: "# {mark} 1"
    insertafter: BOF
    block: |
      global:
        scrape_interval: 10s
      scrape_configs:


- include_tasks: subtasks/set_config.yml
  loop: "{{ lookup('dict', prometheus_ip_list, wantlist=True) }}"

- name: Restart docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_docker_dir }}"
    state: restarted
    