- name: Create Prometheus file
  file:
    path: "{{ prometheus_config }}"
    state: touch

- name: Create glboal
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: "# {mark}"
    insertafter: BOF
    block: |
      global:
        scrape_interval: 10s
      scrape_configs:

- name: Create static_configs
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: ""
    insertafter: "scrape_configs:"
    block: |2
      - job_name: {{ job_name }}
        static_configs:
        - targets:

- name: Insert ips
  lineinfile:
    path: "{{ prometheus_config }}"
    insertafter: '^.*- targets:.*'
    line: "    - {{ item }}"
    state: present
  loop: "{{ prometheus_ip_list }}"

- name: Restart docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ prometheus_docker_dir }}"
    state: restarted
