- name: test
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: "# {mark} global setting"
    insertafter: BOF
    block: |
      global:
        scrape_interval: 10s
        scrape_configs:

- name: test
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: "# {mark} global setting"
    insertafter: "scrape_configs:"
    block: |2
      - job_name: prometheus
        static_configs:
          - targets:


