- stat:
    path: "{{ github_runner_dir }}/run.sh"
  register: run_file_check

- block:
    - stat:
        path: "{{ github_actions_tarball }}"
      register: tarball_file_check

    - name: Download actions runner tarball
      get_url:
        url: "{{ github_action_url }}"
        dest: "{{ github_actions_tarball }}"
      when: not tarball_file_check.stat.exists

    - name: Get file checksum
      stat:
        path: "{{ github_actions_tarball }}"
        checksum_algorithm: sha256
      register: github_action_tar_stat

    - name: Validate the checksum
      fail:
        msg: "Checksum mismatch."
      when: github_action_tar_stat.stat.checksum != github_action_hash

    - name: Extract the installer
      shell: |
        tar xzf ./{{ github_action_tar_file }}
      become_user: "{{ default_user }}"
      args:
        chdir: "{{ github_runner_dir }}"

    - name: Remove file tarball
      file:
        path: "{{ github_actions_tarball }}"
        state: absent

  when: not run_file_check.stat.exists
