- name: Query GitHub API for self-hosted runners
  uri:
    url: "{{ github_list_runners_url }}"
    method: GET
    headers:
      Authorization: "Bearer {{ github_token }}"
      Accept: "application/vnd.github+json"
    return_content: yes
    status_code: 200
  register: github_response_runner_count

- name: Create fresh runner
  block:
    - name: Request registration token from GitHub API for self-hosted runner
      uri:
        url: "{{ github_get_runner_token_url }}"
        method: POST
        headers:
          Accept: application/vnd.github+json
          Authorization: "Bearer {{ github_token }}"
          X-GitHub-Api-Version: "2022-11-28"
        return_content: yes
        status_code: 201
      register: github_response_runner_token

    - set_fact:
        github_runner_token: "{{ github_response_runner_token.json.token }}"
    - debug:
        msg: "{{ github_runner_token }}"
  when: github_response_runner_count.json.total_count == 0

- include_tasks: subtasks/check_current_runners.yml
  loop: "{{ github_response_runner_count.json.runners }}"
  loop_control:
    loop_var: github_response_runner
    label: "{{ github_response_runner }}"
  when: github_response_runner_count.json.total_count != 0
