- include_tasks: docker_compose/create_docker_network.yml
  when:
    item.value.docker_network_name is defined

- include_tasks: docker_compose/clone_docker_repo.yml

- include_tasks: docker_compose/create_dirs.yml
  loop: "{{ item.value.config_dir }}"
  loop_control:
    loop_var: loop_var_dir
    label: "{{ loop_var_dir }}" 
  when:
    item.value.config_dir is defined

- include_tasks: docker_compose/create_env_dirs.yml
  loop: "{{ item.value.env_templates }}"
  loop_control:
    loop_var: loop_var_env_dir
    label: "{{ loop_var_env_dir }}"
  when:
    - item.value.env_templates is defined

- include_tasks: subtasks/create_envs_template.yml
  loop: "{{ item.value.env_templates }}"
  loop_control:
    loop_var: env_template
    label: "{{ env_template }}"

#- include_tasks: subtasks/create_envs.yml
#  loop: "{{ item.value.env_templates }}"
#  loop_control:
#    loop_var: loop_var
#    label: "{{ loop_var }}"
#  when:
#    - item.value.env_templates is defined

- block:
  - name: Check for config dir
    stat:
      path: "{{ item.value.config_repo_dir }}"
    register: config_dir_status
    when:
      - item.value.config_repo_url is defined
      - item.value.config_repo_dir is defined

  - name: Restore config
    git:
      repo: "{{ item.value.config_repo_url }}"
      dest: "{{ item.value.config_repo_dir }}"
    when:
      - item.value.config_repo_url is defined
      - item.value.config_repo_dir is defined
      - not config_dir_status.stat.exists

  - include_tasks: subtasks/setup_push_repo.yml
    loop: "{{ item.value.git_config_push }}"
    loop_control:
      loop_var: loop_var
      label: "{{ loop_var }}"
    when:
      - item.value.git_config_push is defined


- name: "Run docker compose | {{ item.key }}"
  community.docker.docker_compose_v2:
    project_src: "{{ item.value.docker_dir }}"
    state: present


- include_tasks: subtasks/create_nginx_data.yml
  loop: "{{ item.value.nginx_info }}"
  loop_control:
    loop_var: loop_var
    label: "{{ loop_var }}"
  when:
    - item.value.nginx_info is defined
