#
- name: Create static_configs
  blockinfile:
    path: "{{ prometheus_config }}"
    marker: "# {mark} STATIC CONFIG {{ item.key }}"
    insertafter: "# END 1"
    block: |2
      - job_name: {{ item.key }}
        static_configs:
        - targets:
    state: present

#- name: Insert ips
#  lineinfile:
#    path: "{{ prometheus_config }}"
#    insertafter: '^.*- targets:.*'
#    line: "    - {{ item }}"
#    state: present
#  loop: "{{ prometheus_ip_list }}"


- debug:
    msg: "{{ item.key }}"
- debug:
    msg: "{{ item.value }}"
- debug:
    msg: "{{ x }}"
  loop: "{{ item.value }}"
  loop_control:
    loop_var: x
    label: "{{ x }}"
